Ocotlan 1967 Zone A: { scale_meters: 100, scale_pixels: 453, ncolors: 7 }
Ocotlan 2016 Zone A: { scale_meters: 100, scale_pixels: 453, ncolors: 6 }
Ocotlan 1967 Zone B: { scale_meters: 100, scale_pixels: 453, ncolors: 6 }
Ocotlan 2016 Zone B: { scale_meters: 100, scale_pixels: 453, ncolors: 4 }

Mitla 1966 Piedmont: { scale_meters: 500, scale_pixels: 782, ncolors: 5 }
Mitla 1988 Piedmont: { scale_meters: 500, scale_pixels: 782, ncolors: 6 }
Mitla 2016 Piedmont: { scale_meters: 500, scale_pixels: 782, ncolors: 6 }

Mitla HiAll 1966: { scale_meters: 500, scale_pixels: 784, ncolors: 6 }
Mitla HiAll 1988: { scale_meters: 500, scale_pixels: 784, ncolors: 8 }
Mitla HiAll 2016: { scale_meters: 500, scale_pixels: 784, ncolors: 8 }

Mitla Low All 1966: { scale_meters: 500, scale_pixels: 775, ncolors: 6 }
Mitla Low All 1988: { scale_meters: 500, scale_pixels: 775, ncolors: 6 }
Mitla Low All 2016: { scale_meters: 500, scale_pixels: 775, ncolors: 5 }

San Gab Mtn 1966: { scale_meters: 500, scale_pixels: 819, ncolors: 8 }
San Gab Mtn 2016: { scale_meters: 500, scale_pixels: 819, ncolors: 6 }
San Gab South Pied 1966: { scale_meters: 500, scale_pixels: 819, ncolors: 5 }
San Gab South Pied 1988: { scale_meters: 500, scale_pixels: 819, ncolors: 7 }
San Gab South Pied 2016: { scale_meters: 500, scale_pixels: 819, ncolors: 8 }
San Gab North Pied 1966: { scale_meters: 500, scale_pixels: 819, ncolors: 8 }
San Gab North Pied 2016: { scale_meters: 500, scale_pixels: 819, ncolors: 10 }

Rio Sal Zone A 1968: { scale_meters: 100, scale_pixels: 276, ncolors: 6 }
Rio Sal Zone A 2016: { scale_meters: 100, scale_pixels: 276, ncolors: 7 }
Rio Sal Zone B 1968: { scale_meters: 100, scale_pixels: 276, ncolors: 5 }
Rio Sal Zone A 2016: { scale_meters: 100, scale_pixels: 276, ncolors: 6 }

Abasolo 1968: { scale_meters: 100, scale_pixels: 247, ncolors: 6 }
Abasolo 2016: { scale_meters: 100, scale_pixels: 247, ncolors: 7 }

Lambityeco 1966: { scale_meters: 200, scale_pixels: 297, ncolors: 7 }
Lambityeco 2016: { scale_meters: 200, scale_pixels: 297, ncolors: 6 }
